on:
  push:
    branches:
      - local
  workflow_dispatch:

name: Build and Deploy
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Set Timezone
        uses: szenius/set-timezone@v1.1
        with:
          timezoneLinux: "Asia/Seoul"
          timezoneMacos: "Asia/Seoul"
          timezoneWindows: "Asia/Seoul"

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.OS }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.OS }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GP_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages # deploying branch
