on:
  push:
    branches:
      - local
  workflow_dispatch:

name: Build and Deploy
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Use Node.js 24.x
        uses: actions/setup-node@v5
        with:
          node-version: "24.x"
          cache: "pnpm"

      - name: Set Timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Asia/Seoul"
          timezoneMacos: "Asia/Seoul"
          timezoneWindows: "Asia/Seoul"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GP_TOKEN }}
          publish_dir: ./.vitepress/dist
          publish_branch: gh-pages
