on: 
  # push:
  #   branches:
  #     - local
  workflow_dispatch:

name: Build and Deploy
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: renzhaosy/hexo-deploy-action@master
      env:
        PERSONAL_TOKEN: ${{ secrets.GP_TOKEN }}
        PUBLISH_REPOSITORY: kdevkr/kdevkr.github.io # The repository the action should deploy to.
        BRANCH: gh-pages  # The branch the action should deploy to.
        PUBLISH_DIR: ./ # The folder the action should deploy.